# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Gentoo Overlay

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  gentoo-overlay-lint:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3:latest
      env:
        FEATURES: -ipc-sandbox -network-sandbox -pid-sandbox -sandbox -usersandbox
    steps:
      - uses: actions/checkout@v3
      - name: sync gentoo portage tree
        run: emerge-webrsync
      - name: install pkgcheck for linting
        run: emerge --ask=n dev-util/pkgcheck
      - name: Test
        run: pkgcheck scan
